---
- name: Configure automation controller
  hosts: localhost
  become: false
  gather_facts: false
  collections: 
    - ansible.controller 
  tasks:

  - name: Create SQL server project
    project:
      name: MSSQL Project
      organization: Default
      state: present
      scm_update_on_launch: True
      scm_delete_on_update: True
      scm_type: git
      scm_url: https://github.com/johanodell/sql_automation.git