---
- name: Use metrics system role to configure PCP metrics recording
  hosts: "{{ vm_name }}"
  vars: 
    metrics_retention_days: 7
    metrics_from_mssql: yes

  roles: 
    - redhat.rhel_system_roles.metrics

- name: Use metrics system role to configure Grafana
  hosts: "{{ monitor_name }}" 
  vars:
    metrics_monitored_hosts:  ["{{ vm_name }}"]
    
  roles: 
    - redhat.rhel_system_roles.metrics

- name: ensure remote monitoring is possible
  hosts: "{{ vm_name }}"
  tasks:

  - name: Make sure pmproxy is running 
    service: 
      name: pmproxy
      state: started
      enabled: yes 